version: 2
updates:
  - package-ecosystem: npm
    schedule:
      interval: daily
    directory: /
    target-branch: master
    versioning-strategy: increase
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
